source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZJEmoticon_Example', :exclusive => true do
  pod 'ZJEmoticon', :path => '../'
end

target 'ZJEmoticon_Tests', :exclusive => true do
  pod 'ZJEmoticon', :path => '../'

  
end
